Deltares/rtc-tools

.github/workflows/rtc-tools.yml

Add a github workflow based on the gitlab CI workflow.
Private tokens to access codecov and pypi are still missing.
Tests are no longer executed with python 3.8,
since this version is almost end-of-life
and seems to sometimes result in a mysterious crash during package installation, resulting in a message "THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE" for an "unknown package".

workflows: add work flow based on the gitlab ci workflow

---

README.md
doc/getting-started.rst
setup.py
src/rtctools/optimization/modelica_mixin.py
src/rtctools/rtctoolsapp.py
src/rtctools/simulation/simulation_problem.py
tox.ini

The pkg_resources package has been removed from the Python standard
library in version 3.12, while still available when (manually)
installing setuptools. A more modern approach is the usage of
"importlib", available since Python 3.9. Note that we do require a
change to "entry_point" accepting a group parameter that was introduced
with Python 3.10, so we fall back to a version of "importlib_metadata"
that support this. Also note that we also only require this external
(backport) dependency for Python 3.9.

Remove dependency on pkg resources

---

src/rtctools/_internal/casadi_helpers.py

Use a different name for the expression parameter
and catched exception in the is_affine function.

casadi_helpers: fix parameter/variable name

---

src/rtctools/optimization/collocated_integrated_optimization_problem.py

Skip expansion of residual functions if this is not possible. This might be the case when users add custom functions that cannot be expanded.

optimization: fix expansion of residual functions

---

.github/workflows/rtc-tools.yml

pip is now updated in the github worklow. 
This change seems to fix the dependency issue in the pipeline

include pip install in workflow

---

src/rtctools/simulation/io_mixin.py

Only set input variables when calling IOMixin.__set_input_variables.

simulation: fix initialization input variables

---

src/rtctools/simulation/simulation_problem.py

A debug message is added instead of a warning if default values are used in initialization of simulation

sim: warning should not be logged if default values were used

---

src/rtctools/optimization/csv_lookup_table_mixin.py

To avoid infeasibility due to autoscaling, `nlp_scaling_method = none` is passed as `ipopt_options` to the `BSpline1D.fit` method when calling it from the `CSVLookupTableMixin` class.
The `ipopt_options` argument was already included in the `BSpline1D` class in a previous commit. [Commit Link](https://github.com/Deltares/rtc-tools/commit/60b3d2a75dcc61890ffe937808df9fa3d0689563)
This change fixes the failing tests due to numerical issues in Bspline1.

CSVLookupTableMixin: Fix infeasibilities in fitting B-spline due to auto-scaling

---

src/rtctools/optimization/collocated_integrated_optimization_problem.py

The ensemble indices are lists. We already converted the the first ensemble member's to a set, but not the remaining ones. Trying to do `|=` with a list on the right-hand side is not allowed, so we have to explicitly converted to a set first.

CollInt: Fix __debug_check_state_output_scaling for ensemble members

---

src/rtctools/optimization/collocated_integrated_optimization_problem.py

We already have the bounds, and can just pass it along, avoiding an unnecessary call.

CollInt: Avoid unnecessary self.bounds() call

---

CONTRIBUTING.md

Add `--config-settings editable_mode=compat` to editable install instruction.
This ensures that an IDE can correctly locate the source code from an editable install.

CONTRIBUTING: update editable install instruction

---

.coveragerc
.github/workflows/rtc-tools.yml
README.md
sonar-project.properties
tox.ini

Run a code coverage check and let sonarcloud parse it.
The total code coverage percentage will only be visible on sonarcloud after this branch has been merged. For non-main branches, sonarcloud only reports code coverage of new code lines. Since this branch doesn't change any source code, sonarcloud will claim too few lines changed to determine the code coverage.

Add sonar code coverage

---

src/rtctools/rtctoolsapp.py

Fix the copy_libraries function.
The generated library_folders dict should contain
Path rather than string objects.

app: fix copy_libraries

---

src/rtctools/rtctoolsapp.py

On GitLab, the zipfile of the tree that was downloaded contained a folder with the tag name in it. For GitHub however, the folder is names '<group>-<repo>-<sha>', e.g. "Deltares-rtc-tools-1c7b20a". We therefore just find a folder named like that instead.

Fix rtc-tools-download-examples script

---

CONTRIBUTING.md
doc/getting-started.rst

Documentation files _Getting started_ and _Contributing_ now explicitly indicate the supported Python versions (3.9-3.13)

Doc: Update supported Python versions

---

src/rtctools/optimization/collocated_integrated_optimization_problem.py
tests/optimization/test_integration.py

The check to see if the parameters were constant/equal over all ensemble members was wrong. The if statement would evaluate to 'true' for e.g. `[1, 0.5]`. We would then erroneously use the same parameter value of `1` for all members.
In more detail on what exactly was happening:
`np.all(values)` evaluates to `np.True_`
`np.True == values[0]` casts the left-hand side to a float/int, so it
becomes
`1.0 == values[0]` which is True if the first member is 1 (or 1.0)
We add a test case to cover this scenario, by mostly copy-pasting an existing one for ensembles, but adjusting it to vary the _parameter_ value instead.

CollInt: Fix ensemble-varying parameters if first member value is 1

---

src/rtctools/optimization/collocated_integrated_optimization_problem.py

Internally the `times` were already returned with the `__states_time_in` method. Exposing this functinality to the user will allow them to e.g. compute integrals/sums of algebraic states/control inputs.
Our implementation of `integral` takes averages over a time step, which makes sense for state variables like reservoir volumes. But if one is interested in a sum/average of algebraic states, they would want to exclude the value at t0 (assuming backwards euler). This is non-trivial, and would mean the user has to reimplent the logic in `__states_time_in` for history etc.
Note that we may want to support different ways of calculating the integral directly in `integral()` in the future, but at least optionally returning the times from `states_in()` in this commit already allows this and more …

CollInt: Support returning times from 'states_in()'

---

src/rtctools/_internal/casadi_helpers.py
tests/optimization/test_interpolation.py

Other interpolation tests already cover a variable with different time steps than the overall collocation time steps. In the case where this 'different' means just a _single_ time step, the interpolation with CasADi would fail.
Note that 'interp1d' already extrapolated outside the range of `ts`, it just refused to do so for a single timestep.

CollInt/casadi_helpers: Fix interpolation for single-timestep variables

---

src/rtctools/optimization/collocated_integrated_optimization_problem.py
tests/optimization/test_debug_checks.py

CollInt/_debug_*: Fix tol_down warnings in coefficient check

---

pyproject.toml

A `<= 3.7` is equivalent to `<= 3.7.0`. We want to allow the entire 3.7 series of CasADi, and with `<= 3.7.*` not being allowed, we use `< 3.8`.

pyproject.toml: Fix allowing CasADi 3.7.*
